services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5602:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


  mongodb:
    image: mongodb/mongodb-atlas-local:8.3.4
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=root
    ports:
      - "27018:27017"
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
      - mongodbsearch:/data/mongot
    networks:
      - elk
volumes:
  esdata:
  mongodbdata:
  mongodbconfig:
  mongodbsearch:

networks:
  elk:
    driver: bridge
